version: '3'

services:
  app:
    build: .
    ports:
      - 8081:80
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - SQLITE_DATABASE=mydb
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 127.0.0.1
    volumes:
      - nextcloud:/var/www/html
      - ..:/var/www/html/custom_apps/nextpod
      - ./nextpod.config.php:/var/www/html/config/nextpod.config.php

volumes:
  nextcloud:
